version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  build:
    commands:
      - echo Building Node code ...
      - npm install
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - "**/*"
